// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXb18X8b_-Hu5pXOuWdzQ7GlllLdoB4U0',
    appId: '1:742679725855:web:c8d0445d70a86cc787122a',
    messagingSenderId: '742679725855',
    projectId: 'conaeingeo',
    authDomain: 'conaeingeo.firebaseapp.com',
    databaseURL: 'https://conaeingeo-default-rtdb.firebaseio.com',
    storageBucket: 'conaeingeo.appspot.com',
    measurementId: 'G-N21YCN32JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlqNsPLWtNPjzlIGzRZUl-_EULYgYScU',
    appId: '1:742679725855:android:c8294eb81f8181d287122a',
    messagingSenderId: '742679725855',
    projectId: 'conaeingeo',
    databaseURL: 'https://conaeingeo-default-rtdb.firebaseio.com',
    storageBucket: 'conaeingeo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHRTvfUcSCmiwb_kAYVX87yB-yCSEKIW4',
    appId: '1:742679725855:ios:bb497fb308aeda1687122a',
    messagingSenderId: '742679725855',
    projectId: 'conaeingeo',
    databaseURL: 'https://conaeingeo-default-rtdb.firebaseio.com',
    storageBucket: 'conaeingeo.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHRTvfUcSCmiwb_kAYVX87yB-yCSEKIW4',
    appId: '1:742679725855:ios:f61e094ae3a08f4987122a',
    messagingSenderId: '742679725855',
    projectId: 'conaeingeo',
    databaseURL: 'https://conaeingeo-default-rtdb.firebaseio.com',
    storageBucket: 'conaeingeo.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
